name: Create Pull Request

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Make some changes, e.g., update a file
        echo "Some changes" >> somefile.txt
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated changes by GitHub Actions"

    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated changes by GitHub Actions
        committer: GitHub <noreply@github.com>
        author: Your Name <your-email@example.com>
        title: "Automated PR: Changes to somefile.txt"
        body: |
          This is an automated pull request generated by GitHub Actions.
        base: main
        branch: automated-changes-branch  # The branch to create the PR from

    - name: Output Pull Request URL
      run: echo "Pull request URL: ${{ steps.create-pull-request.outputs.pull-request-url }}"
