name: PR Validation for Salesforce Metadata

on:
  pull_request:
    branches:
      - main
      - QA

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Print environment variables
        run: printenv

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt

      - name: Validate Metadata
        run: sfdx force:source:deploy --checkonly --sourcepath force-app/main/default --target-org jp@sunsolutions.com

  run-tests:
    runs-on: ubuntu-latest

    needs: validate  # Ensure 'validate' job completes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Print environment variables
        run: printenv

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt

      - name: Debug Test Classes File
        run: cat test-classes.txt

      - name: Read Test Class Names from File
        id: read-test-classes
        run: |
          TEST_CLASSES=$(cat test-classes.txt | tr '\n' ',' | sed 's/,$//')
          echo "TEST_CLASSES=$TEST_CLASSES" >> $GITHUB_ENV

      - name: Run Specific Apex Tests
        run: |
          sfdx force:apex:test:run -n "$TEST_CLASSES" -r human -u jp@sunsolutions.com
