name: PR Validation for Salesforce Metadata

on:
  pull_request:
    branches:
      - QA
      

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Print environment variables
        run: printenv

      - name: Authenticate to Salesforce
        run: |
          echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt

      - name: Debug Test Classes File
        run: cat test-classes.txt

      - name: Read Test Class Names from File
        id: read-test-classes
        run: |
          TEST_CLASSES=$(cat test-classes.txt | tr '\n' ',' | sed 's/,$//')
          if [ -z "$TEST_CLASSES" ]; then
            echo "TEST_CLASSES=" >> $GITHUB_ENV
            echo "RUN_TESTS=false" >> $GITHUB_ENV
          else
            echo "TEST_CLASSES=$TEST_CLASSES" >> $GITHUB_ENV
            echo "RUN_TESTS=true" >> $GITHUB_ENV
          fi

      - name: Run Specific Apex Tests
        if: env.RUN_TESTS == 'true'
        run: |
          sfdx force:apex:test:run -n ${{ env.TEST_CLASSES }} -r human -u jp@sunsolutions.com

      - name: Detect Changed Files
        id: changed-files
        run: |
          git fetch origin
          CHANGED_FILES=$(git diff --name-only origin/QA..HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "$CHANGED_FILES"
          
      - name: Filter Apex and Metadata Files
        id: filter-files
        run: >
          APEX_CLASSES=$(echo "$CHANGED_FILES" | grep -E
          '\.cls$|\.trigger$|\.page$|\.component$' || true)

          META_FILES=$(echo "$CHANGED_FILES" | grep -E '\.xml$' || true)


          if [ -z "$APEX_CLASSES" ] && [ -z "$META_FILES" ]; then
            echo "VALIDATE=false" >> $GITHUB_ENV
          else:
            echo "VALIDATE=true" >> $GITHUB_ENV
            echo "APEX_CLASSES=$APEX_CLASSES" >> $GITHUB_ENV
            echo "META_FILES=$META_FILES" >> $GITHUB_ENV
          fi
          
      - name: Run Apex Tests
        if: env.VALIDATE == 'true' && env.APEX_CLASSES != ''
        run: >
          TEST_CLASSES=$(echo "${{ env.APEX_CLASSES }}" | tr '\n' ',' | sed 's/,$//')

          sfdx force:apex:test:run -n $TEST_CLASSES -r human -u jp@sunsolutions.com 

      - name: Validate Metadata
        if: env.VALIDATE == 'true'
        run: >
          sfdx force:source:deploy --checkonly --sourcepath force-app/main/default
          --target-org jp@sunsolutions.com  --testlevel RunSpecifiedTests
          --runtests "${{ env.APEX_CLASSES }}"

