name: Validate Salesforce Metadata

on:
  push:
    branches:
      - feature/** # Trigger validation on commits to any feature branch
  pull_request:
    branches:
      - main # Optionally trigger validation on PRs to the main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1
      with:
        version: latest

    - name: Authenticate to Salesforce
      run: |
        echo ${SF_AUTH_URL} > sfdx-auth-url.txt
        sfdx auth:sfdxurl:store --sfdxurlfile sfdx-auth-url.txt --setdefaultusername

    - name: Validate Metadata
      run: sfdx force:source:deploy --checkonly --sourcepath force-app/main/default --targetusername=default