name: PR Validation for Salesforce Metadata

on:
  pull_request:
    branches:
      - main # Trigger validation on PRs to the main branch
      - Dev
      - QAT
      - Prod

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1
      with:
        version: latest

    - name: Print environment variables
      run: printenv

    - name: Authenticate to Salesforce
      run: |
        echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
        sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt

    - name: Validate Metadata
      run: sfdx force:source:deploy --checkonly --sourcepath force-app/main/default --target-org jp@sunsolutions.com

    - name: Run Apex Tests
      run: |
        sfdx force:apex:test:run --result-format human --target-org jp@sunsolutions.com