name: PR Validation for Salesforce Metadata

on:
  pull_request:
    branches:
      - main # Trigger validation on PRs to the main branch
      - develop # Optionally add other branches as needed

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Salesforce CLI
      run: |
        npm install @salesforce/cli --global
        sf --help
        pip install xq
        pip install yq

    - name: Install sfdxGit delta
      run: |
        echo y | sf plugins install sfdx-git-delta
        sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output "." --igonre .github/workflows/ignore.txt
        cat package/package.xml


    - name: Set up Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1
      with:
        version: latest

    - name: Authenticate to Salesforce
      run: |
        echo ${{ secrets.SF_AUTH_URL }} > sfdx-auth-url.txt
        sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt

    - name: Validate Metadata
      run: sfdx force:source:deploy --checkonly --sourcepath force-app/main/default --targetusername jp@sunsolutions.com