name: SFDC Deploy Delta Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: karamchandanid/sfdc-credentials-auth@v2
        id: sfdc_auth
        with:
          sfdc_client_id: ${{ secrets.SFDC_CLIENT_ID }}
          sfdc_client_secret: ${{ secrets.SFDC_CLIENT_SECRET }}
          user_name: ${{ secrets.SFDC_DEV_USERNAME }}
          password: ${{ secrets.SFDC_DEV_PASSWORD }}
          login_url: https://orgfarm-ea4276b2f3-dev-ed.develop.my.salesforce.com


      - name: Set Auth Environment Variables
        run: |
          echo "ACCESS_TOKEN=${{ steps.sfdc_auth.outputs.access_token }}" >> $GITHUB_ENV
          echo "INSTANCE_URL=${{ steps.sfdc_auth.outputs.instance_url }}" >> $GITHUB_ENV

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      - name: Install sfdx-git-delta Plugin
        run: |
          sfdx plugins:install sfdx-git-delta

      - name: Generate Delta Package
        run: |
          git fetch origin main
          git diff --name-only origin/main...HEAD
          sfdx sgd:source:delta --to HEAD --from origin/main --output delta --generate-delta

      - name: Deploy Delta to UAT
        run: |
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SFDC_UAT_USERNAME }} --instanceurl https://test.salesforce.com -a UAT
          sfdx force:source:deploy -u UAT -x delta/package/package.xml --testlevel RunLocalTests --wait 10
