name: Validate Feature Branch

on:
  push:
    branches:
      - 'feature/*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate to Dev Hub
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: sfdx auth:sfdxurl:store -f sfdx_auth_url.txt -a DevHub

      - name: Create Scratch Org
        run: sfdx force:org:create -s -f config/project-scratch-def.json -a FeatureOrg

      - name: Push source to Scratch Org
        run: sfdx force:source:push -u FeatureOrg

      - name: Run Apex tests
        run: sfdx force:apex:test:run -u FeatureOrg --resultformat human --wait 10

      - name: Delete Scratch Org
        if: always()
        run: sfdx force:org:delete -u FeatureOrg -p
